name: mycar
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.6+4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  provider: ^4.1.2
  responsive_screen: ^1.0.0
  path_provider: ^1.6.10


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Amble
      fonts:
        - asset: lib/fonts/Amble-Regular.ttf
